sudo: false

language: python
python:
  - 3.6

services:
  - docker

script:
  - cd instarest/
  - mkdir shared
  - docker-compose build
  - docker-compose run -v "$PWD/shared:/shared" django pytest --cov=./
  - bash <(curl -s https://codecov.io/bash)
