sudo: true

services:
  - docker

script:
  - cd instarest/
  - mkdir shared
  - docker-compose run -v "$PWD/shared:/shared" django pytest --cov=./
  - cat shared/coverage.txt
  - bash <(curl -s https://codecov.io/bash)

after_success:
- codecov
