sudo: false

language: python
python:
  - 3.6

services:
  - docker



script:
  - cd instarest/
  - mkdir shared
  - docker-compose build
  - mkdir shared & docker-compose run -itv "$PWD/shared:/shared"  && curl -s https://codecov.io/bash | bash -
