sudo: false

language: python
python:
  - 3.6

services:
  - docker


before_install:
  - cd instarest/
  - mkdir shared
  - docker-compose build

script:
  - mkdir shared & docker-compose run -itv "$PWD/shared:/shared"  && curl -s https://codecov.io/bash | bash -
