sudo: false

language: python
python:
  - 3.6

services:
  - docker

script:
  - cd instarest/
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker-compose run $ci_env  django pytest --cov=./ && bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://codecov.io/bash)

after_success:
- codecov
