sudo: false

language: python
python:
  - 3.6

services:
  - docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  # Declare cache folder
  bundler: true
  directories:
    - $HOME/docker

script:
  - cd instarest/
  - mkdir shared
  - docker-compose build
  - docker-compose run -itv "$PWD/shared:/shared"
  - curl -s https://codecov.io/bash | bash -
